### ISSUE TITLE
repeated integers bug

### ISSUE THREAD

**Issue by ilsenatorov** [ilsenatorov/Simple-Games#1]
if you type in repeated digits it breaks:

Please make a guess:444
Your guess contains repeat digits!
Traceback (most recent call last):
  File "/home/ilsenatorov/bin/BullsCows.py", line 107, in <module>
    game()
  File "/home/ilsenatorov/bin/BullsCows.py", line 103, in game
    game()
  File "/home/ilsenatorov/bin/BullsCows.py", line 99, in game
    PlayTheGame(Tries)
  File "/home/ilsenatorov/bin/BullsCows.py", line 79, in PlayTheGame
    print("You have " + TriesLeft + "Tries left!")
TypeError: Can't convert 'int' object to str implicitly

**Comment by ilsenatorov** [comment]
solved
